In [1]:

import pandas as pd
import requests

In [2]:
data=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key={my_api_Key}&language=en-US&page=1")

In [20]:
data.json()['total_pages']

540

In [19]:
pd.DataFrame(data.json()['results'])[['id','title','release_date','vote_average','vote_count','popularity']]

,id,title,release_date,vote_average,vote_count,popularity
0,278,The Shawshank Redemption,1994-09-23,8.718,30151,43.3695
1,238,The Godfather,1972-03-14,8.686,22778,42.0565
2,240,The Godfather Part II,1974-12-20,8.571,13803,24.3546
3,424,Schindler's List,1993-12-15,8.567,17336,24.1763
4,389,12 Angry Men,1957-04-10,8.559,9903,18.1667
5,129,Spirited Away,2001-07-20,8.534,18183,29.7691
6,155,The Dark Knight,2008-07-16,8.528,35532,32.9229
7,19404,Dilwale Dulhania Le Jayenge,1995-10-20,8.515,4573,14.3986
8,497,The Green Mile,1999-12-10,8.504,19102,24.2955
9,122,The Lord of the Rings: The Return of the King,2003-12-17,8.496,26353,30.3274
10,496243,Parasite,2019-05-30,8.494,20455,33.5378
11,1181678,¿Quieres ser mi hijo?,2023-09-21,8.490,315,14.7546
12,680,Pulp Fiction,1994-09-10,8.485,30025,33.8807
13,372058,Your Name.,2016-08-26,8.477,12436,24.4444
14,157336,Interstellar,2014-11-05,8.470,39442,59.4178
15,429,"The Good, the Bad and the Ugly",1966-12-23,8.468,9560,21.3774
16,13,Forrest Gump,1994-06-23,8.464,29561,26.6303
17,769,GoodFellas,1990-09-12,8.453,14221,22.8735
18,346,Seven Samurai,1954-04-26,8.453,4185,14.7981
19,12477,Grave of the Fireflies,1988-04-16,8.444,6466,0.0154

In [51]:
movies= pd.DataFrame()

In [52]:
for i in range(1,540):
  data=requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key=4f9c739cc3b5ae2fcc79237db9e1f869&language=en-US&page={i}")
  if data.status_code==200:
    temp_df=pd.DataFrame(data.json()['results'])[['id','title','release_date','vote_average','vote_count','popularity']]
    movies=pd.concat([movies, temp_df], ignore_index=True)

In [53]:
movies

,id,title,release_date,vote_average,vote_count,popularity
0,278,The Shawshank Redemption,1994-09-23,8.718,30151,43.3695
1,238,The Godfather,1972-03-14,8.686,22778,42.0565
2,240,The Godfather Part II,1974-12-20,8.571,13803,24.3546
3,424,Schindler's List,1993-12-15,8.567,17336,24.1763
4,389,12 Angry Men,1957-04-10,8.559,9903,18.1667
...,...,...,...,...,...,...
9995,58444,Women Vs Men,2011-02-04,5.500,636,0.5986
9996,10481,102 Dalmatians,2000-10-07,5.501,1460,2.7354
9997,1499,Teenage Mutant Ninja Turtles III,1993-03-17,5.501,903,3.7092
9998,18009,Leprechaun 2,1994-04-08,5.500,362,1.8784
9999,7840,"10,000 BC",2008-03-04,5.499,3148,4.7706

In [55]:
movies.to_csv('movies.csv')